/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_zoo_pytorch_PytorchModel */

#ifndef _Included_com_intel_analytics_zoo_pytorch_PytorchModel
#define _Included_com_intel_analytics_zoo_pytorch_PytorchModel
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_intel_analytics_zoo_pytorch_PytorchModel
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_pytorch_PytorchModel_load
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_intel_analytics_zoo_pytorch_PytorchModel
 * Method:    forward
 * Signature: ([FI[I)Lcom/intel/analytics/zoo/pipeline/inference/JTensor;
 */
JNIEXPORT jobject JNICALL Java_com_intel_analytics_zoo_pytorch_PytorchModel_forward
  (JNIEnv *, jobject, jfloatArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
