/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <cstring>
#include "com_intel_analytics_zoo_aep_AEPHandler.h"

/*
 * Class:     com_intel_analytics_zoo_aep_AEPHandler
 * Method:    initialize
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_aep_AEPHandler_initialize
  (JNIEnv *, jclass, jstring, jlong) {}

/*
 * Class:     com_intel_analytics_zoo_aep_AEPHandler
 * Method:    allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_zoo_aep_AEPHandler_allocate
  (JNIEnv *, jclass, jlong size) {
  char *addr = new char(size);
  return (long)addr;
  }

/*
 * Class:     com_intel_analytics_zoo_aep_AEPHandler
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_aep_AEPHandler_free
  (JNIEnv *, jclass, jlong addr) {
       char * p = (char *)addr;
       delete p;
  }

/*
 * Class:     com_intel_analytics_zoo_aep_AEPHandler
 * Method:    copy
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_aep_AEPHandler_copy
  (JNIEnv *, jclass, jlong dest, jlong src, jlong size) {
    memcpy((void *)dest, (void *)src, size);
 }