/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "/home/lizhichao/bin/god/memkind/memkind.h"
/* Header for class com_intel_analytics_zoo_aep_AEPHandler */

#ifndef _Included_com_intel_analytics_zoo_aep_AEPHandler
#define _Included_com_intel_analytics_zoo_aep_AEPHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_zoo_aep_AEPHandler
 * Method:    initialize
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_aep_AEPHandler_initialize
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_intel_analytics_zoo_aep_AEPHandler
 * Method:    allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_zoo_aep_AEPHandler_allocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_zoo_aep_AEPHandler
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_aep_AEPHandler_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_zoo_aep_AEPHandler
 * Method:    copy
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_aep_AEPHandler_copy
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
