/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_analytics_zoo_aep_AEPSimulator */

#ifndef _Included_com_intel_analytics_zoo_aep_AEPSimulator
#define _Included_com_intel_analytics_zoo_aep_AEPSimulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_analytics_zoo_aep_AEPSimulator
 * Method:    initAEP
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_aep_AEPSimulator_initAEP
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_intel_analytics_zoo_aep_AEPSimulator
 * Method:    allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_analytics_zoo_aep_AEPSimulator_allocate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_zoo_aep_AEPSimulator
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_analytics_zoo_aep_AEPSimulator_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_analytics_zoo_aep_AEPSimulator
 * Method:    get
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_intel_analytics_zoo_aep_AEPSimulator_get
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
